### ISSUE TITLE
Fake tickets will cause system updates to fail.

### ISSUE THREAD

**Issue by TurdPooCharger** [MechanicalDragon0687/TWLFix-CFW#1]
If you dump these titles as standard built CIAs in GodMode9, reinstall them in FBI, and then delete just the titles while leaving behind their fake/spoofed tickets, trying to update the 3DS firmware in Recovery Mode or System Settings will not allow the 3DS system to re-download legit copies.

- 0004013800000102 - Old_3DS TWL_FIRM 
- 0004013820000102 - New_3DS TWL_FIRM
- 0004800542383841 - NINTENDO DSi (DS INTERNET)
- 00048005484E4441 - DS Download Play
- 0004800F484E4841 - Nintendo DS Cart Whitelist
- 0004800F484E4C41 - TWL Version Data

However, if you delete the fake tickets in FBI and try again, they will then be redownloaded with legit tickets. `0004800F484E4C41 - TWL Version Data` is the only title that is not restored.

**Comment by MechanicalDragon0687** [comment]
true, if you screw up your tickets and install cias instead of using this app, it will break your ability to redownload them from the eshop.

This app will still function correctly, but your ability to redownload the apps will still be broken and the best option would be to restore the NAND backup that was made when installing CFW initially.
